# Generated by Django 4.0.6 on 2022-07-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_phone_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Prod name')),
                ('price', models.IntegerField(verbose_name='Prod price')),
                ('img', models.ImageField(upload_to='media', verbose_name='Prod image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catprod', to='main.category')),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watchs',
            },
        ),
        migrations.DeleteModel(
            name='Nout',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.DeleteModel(
            name='Watch',
        ),
    ]
