# Generated by Django 4.0.6 on 2022-07-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_prod_delete_nout_delete_phone_delete_watch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prod',
            options={'verbose_name': 'Prod', 'verbose_name_plural': 'Prods'},
        ),
    ]
